Systems and UI
nicolasfara/ecscala pull request #100
Opened 2021-09-26 13:06 UTC by vitlinda

This PR introduces the `RenderingSystem`, the `MovementSystem` and the `FrictionSystem` along with the demo UI.
Closes #92 
Closes #88 
Closes #87

2021-09-26 13:18 UTC, ndido98 requested changes

2021-09-26 13:18 UTC, ndido98 commented on demo/src/main/scala/dev/atedeg/ecscalademo/SimulationStatus.scala
> +  val gravity = 9.81
In #99 they are in `EnvironmentState.scala`, where should we put them? @nicolasfara @giacomocavalieri

2021-09-26 13:18 UTC, ndido98 commented on demo/src/main/scala/dev/atedeg/ecscalademo/controller/MainViewController.scala
> +    } world hasAn entity withComponents { Circle(radius, color) &: position &: velocity }
You're missing the `Mass` component

2021-09-26 13:18 UTC, ndido98 commented on demo/src/test/scala/dev/atedeg/ecscalademo/systems/FrictionSystemTest.scala
> +          (ball, Velocity(Vector(298.5285, 0)) &: CNil),
You can just check that the velocity has decreased if you prefer, so you can make a simpler test and remove that magic number

2021-09-26 14:14 UTC, giacomocavalieri requested changes

2021-09-26 14:14 UTC, giacomocavalieri commented on demo/src/main/scala/dev/atedeg/ecscalademo/ECSCanvas.scala
> +   *   The strating point from where draw the line.
```suggestion
   *   The starting point of the line.
```

2021-09-26 14:14 UTC, giacomocavalieri commented on demo/src/main/scala/dev/atedeg/ecscalademo/ECSCanvas.scala
> +   *   The end point up to where draw the line.
```suggestion
   *   The end point of the line.
```

2021-09-26 14:14 UTC, giacomocavalieri commented on demo/src/main/scala/dev/atedeg/ecscalademo/systems/MovementSystem.scala
> +    val Position(point) &: Velocity(vector) &: CNil = components
To me it read better like this
```suggestion
    val Position(position) &: Velocity(velocity) &: CNil = components
```

2021-09-26 14:14 UTC, giacomocavalieri commented on demo/src/main/scala/dev/atedeg/ecscalademo/systems/RenderSystem.scala
> +    val lineWidth = PlayState.selectedBall match { case Some(`entity`) => 3; case _ => 1 }
This are magic numbers, what is 3?  What is 1? They could become variables named `selectedBallLineWidth` and `regularBallLineWidth`

2021-09-27 14:05 UTC, vitlinda commented on demo/src/main/scala/dev/atedeg/ecscalademo/SimulationStatus.scala
> +    Position(Point(581, 198)),
This is going to be done with the next PlayState implementation

2021-09-27 14:07 UTC, vitlinda commented on demo/src/main/scala/dev/atedeg/ecscalademo/systems/FrictionSystem.scala
> +      if ((velocity dot newVelocity) < 0) Velocity(Vector(0, 0)) &: CNil else Velocity(newVelocity) &: CNil
Your are right, according to [https://docs.scala-lang.org/scala3/book/taste-control-structures.html](url)

2021-09-27 14:19 UTC, nicolasfara approved these changes

2021-09-27 14:31 UTC, ndido98 approved these changes

2021-09-27 16:21 UTC, giacomocavalieri approved these changes

2021-09-27 16:21 UTC, merged