DSL syntax refactor
nicolasfara/ecscala pull request #104
Opened 2021-09-28 17:55 UTC by vitlinda

This PR introduces a major refactor of the DSL, a removeSystem method (both in `World's` trait and in the DSL) and adds the DSL syntax for the excluding `View`.
Closes #56 
Closes #85

2021-09-28 18:17 UTC, ndido98 approved these changes

2021-09-28 19:09 UTC, giacomocavalieri requested changes

2021-09-28 19:09 UTC, giacomocavalieri commented on core/src/main/scala/dev/atedeg/ecscala/dsl/Syntax.scala
> +  case class ClearAllFromWorld(clearWord: ClearWord) extends From[World, Unit] {
Why does it take a `ClearWord` as a parameter if it does nothing with it? I would remove the `ClearWord` altogether

2021-09-28 19:09 UTC, giacomocavalieri commented on core/src/main/scala/dev/atedeg/ecscala/dsl/Syntax.scala
> +  private[dsl] case class ClearWord()
I would remove this as it serves no purpose, read my comment above

2021-09-28 19:09 UTC, giacomocavalieri commented on core/src/test/scala/dev/atedeg/ecscala/WorldTest.scala
> +        }
Why didn't you use the `SystemBuilder`

2021-09-28 19:09 UTC, giacomocavalieri commented on core/src/test/scala/dev/atedeg/ecscala/dsl/ECScalaDSLTest.scala
> +      }
Why didn't you use the `SystemBuilder`

2021-09-28 19:09 UTC, giacomocavalieri commented on core/src/test/scala/dev/atedeg/ecscala/dsl/ECScalaDSLTest.scala
> +      }
Why didn't you use the `SystemBuilder`?

2021-09-28 19:09 UTC, giacomocavalieri commented on core/src/test/scala/dev/atedeg/ecscala/dsl/ECScalaDSLTest.scala
> +  "geView[Position &: CNil] excluding[Velocity &: CNil] from world" should {
```suggestion
  "geView[Position &: CNil].excluding[Velocity &: CNil] from world" should {
```

2021-09-28 20:46 UTC, nicolasfara requested changes

2021-09-28 20:46 UTC, nicolasfara commented on core/src/main/scala/dev/atedeg/ecscala/dsl/Syntax.scala
> +   * This trait enables the use of the word "from" in the dsl
Missing a `.` at the end of the sentence

2021-09-28 21:21 UTC, nicolasfara approved these changes

2021-09-29 05:56 UTC, giacomocavalieri approved these changes

2021-09-29 05:56 UTC, merged