DSL syntax
nicolasfara/ecscala pull request #114
Opened 2021-09-30 14:10 UTC by vitlinda

Closes #109

2021-09-30 14:15 UTC, ndido98 approved these changes

2021-09-30 14:15 UTC, ndido98 commented on core/src/test/scala/dev/atedeg/ecscala/fixtures/SystemFixture.scala
> +//import scala.language.implicitConversions
Remove

2021-09-30 16:07 UTC, nicolasfara approved these changes

2021-09-30 16:36 UTC, giacomocavalieri requested changes

2021-09-30 16:36 UTC, giacomocavalieri commented on core/src/main/scala/dev/atedeg/ecscala/dsl/Conversions.scala
>     * This conversion enable the removal of a single component from an entity with the following syntax:
```suggestion
   * This conversion enables the removal of a single component from an entity with the following syntax:
```

2021-09-30 16:36 UTC, giacomocavalieri commented on core/src/main/scala/dev/atedeg/ecscala/dsl/ECScalaDSL.scala
> + *   * remove mySystem from world
Are you sure this code compiles even if you have no brackets around `mySystem`?

2021-09-30 16:36 UTC, giacomocavalieri commented on core/src/test/scala/dev/atedeg/ecscala/dsl/ECScalaDSLTest.scala
>    "clearAll from world" should {
```suggestion
  "clearAllEntities from world" should {
```

2021-09-30 16:36 UTC, giacomocavalieri commented on core/src/test/scala/dev/atedeg/ecscala/fixtures/SystemFixture.scala
> +  }
If you are not specifying any before and after you can simply implement a System with:
```scala
System[Position &: CNil] { (_, components, _) =>
  val Position(x, y) &: CNil = c
  Position(x + 3, y + 3) &: CNil
}
```
It is way more readable

2021-09-30 16:36 UTC, giacomocavalieri commented on core/src/test/scala/dev/atedeg/ecscala/fixtures/SystemFixture.scala
> +}
Same as above

2021-10-01 14:57 UTC, giacomocavalieri requested changes

2021-10-01 14:57 UTC, giacomocavalieri commented on core/src/main/scala/dev/atedeg/ecscala/dsl/ECScalaDSL.scala
> + *   * remove (mySystem) from world
We used `{}` in all other single-parameter examples, here you are using `()`, pick one and stick with it

2021-10-01 14:57 UTC, giacomocavalieri commented on core/src/main/scala/dev/atedeg/ecscala/dsl/ECScalaDSL.scala
> +   */
In all this `remove` methods I would shortly describe what is removed from what

2021-10-02 12:31 UTC, giacomocavalieri approved these changes

2021-10-02 12:32 UTC, merged