Fix and improvements to the demo
nicolasfara/ecscala pull request #117
Opened 2021-09-30 17:16 UTC by nicolasfara

In this PR fix/introduce:
- Parallel execution of the tests in sbt
- Add Finite State Machine to control the game state
- Add UI element in order to tune `Wall restitution` and `Friction coefficient`
- Refactor `PlayState`, `MouseState` and `EnvironmentState` in order to avoid race condition in test execution

Closes #105 
Closes #106

2021-09-30 18:22 UTC, ndido98 requested changes

2021-09-30 18:22 UTC, ndido98 commented on demo/src/test/scala/dev/atedeg/ecscalademo/fixtures/VelocityFixture.scala
> -import dev.atedeg.ecscalademo.given
Did you intentionally remove the `given`?

2021-09-30 18:25 UTC, nicolasfara commented on demo/src/test/scala/dev/atedeg/ecscalademo/fixtures/VelocityFixture.scala
> -import dev.atedeg.ecscalademo.given
Yes, is not used in the trait

2021-09-30 19:12 UTC, giacomocavalieri requested changes

2021-09-30 19:12 UTC, giacomocavalieri commented on demo/src/test/scala/dev/atedeg/ecscalademo/systems/VelocityArrowSystemTest.scala
> +    "run if the game is paused, there is a selected ball and the game is in velocity editing mode" in new VelocityArrowFixture {
```suggestion
    "run if the game is in changeVelocity mode and there is a selected ball" in new VelocityArrowFixture {
```

2021-09-30 19:12 UTC, giacomocavalieri commented on demo/src/test/scala/dev/atedeg/ecscalademo/systems/VelocityArrowSystemTest.scala
> -      verify(canvas, times(1)).drawLine(is(Point(0, 0)), is(Point(10, 10)), any(), anyDouble())
Why did you remove the `times(1)`?

2021-09-30 19:12 UTC, giacomocavalieri commented on demo/src/test/scala/dev/atedeg/ecscalademo/systems/VelocityEditingSystemTest.scala
> +      mState: MouseState,
I really can't stand abbreviations
```suggestion
      world: World,
      system: VelocityEditingSystem,
      playState: PlayState,
      mouseState: MouseState,
```

2021-09-30 19:15 UTC, vitlinda approved these changes

2021-09-30 19:27 UTC, nicolasfara commented on demo/src/test/scala/dev/atedeg/ecscalademo/systems/VelocityArrowSystemTest.scala
> -      verify(canvas, times(1)).drawLine(is(Point(0, 0)), is(Point(10, 10)), any(), anyDouble())
`Verify()` implicit assume that the method is called once

2021-09-30 19:31 UTC, nicolasfara commented on demo/src/test/scala/dev/atedeg/ecscalademo/systems/VelocityEditingSystemTest.scala
> +      mState: MouseState,
Those abbreviation in needed due a clash of name in the fixture. If clash happen the test fail

2021-10-01 13:20 UTC, ndido98 approved these changes

2021-10-02 15:14 UTC, giacomocavalieri approved these changes

2021-10-02 17:01 UTC, merged