World implementation
nicolasfara/ecscala pull request #46
Opened 2021-08-22 14:40 UTC by vitlinda

This PR introduces a first implementation of the `World` and `Component` traits.
It also implements a `TypeTag` trait which is used to perform runtime checks on the compile time type of the components.
Lastly, implements a `ComponentsContainer` which is used to store maps from an Entity to Components of a specific type.

Closes #34 #35 #36

2021-08-22 16:04 UTC, nicolasfara approved these changes

2021-08-22 16:04 UTC, nicolasfara commented on src/main/scala/dev/atedeg/ecscala/Component.scala
> +trait Component {
It might be useful to provide the scaladoc for this trait, right?

2021-08-22 16:13 UTC, nicolasfara approved these changes

2021-08-22 16:55 UTC, giacomocavalieri approved these changes

2021-08-22 17:12 UTC, ndido98 requested changes

2021-08-22 17:12 UTC, ndido98 commented on src/main/scala/dev/atedeg/ecscala/util/Event.scala
> +}
There is no way to unregister handlers.

2021-08-22 17:12 UTC, ndido98 commented on src/main/scala/dev/atedeg/ecscala/util/Event.scala
> +  def apply[T](): Event[T] = new EventImpl[T](Seq())
Is that `[T]` necessary?

2021-08-22 17:12 UTC, ndido98 commented on src/main/scala/dev/atedeg/ecscala/util/immutable/ComponentsContainer.scala
> +      componentsMap.get(tt) map (_.asInstanceOf[Map[Entity, T]])
I'd leave a line or two of comment explaining why this cast is here and why it's safe to do so.

2021-08-22 17:12 UTC, ndido98 commented on src/main/scala/dev/atedeg/ecscala/util/immutable/ComponentsContainer.scala
> +        map filterNot ((e, c) => e == entity && c.eq(component))
Why did you use `eq` instead of `==`?

2021-08-22 17:12 UTC, ndido98 commented on src/main/scala/dev/atedeg/ecscala/util/immutable/ComponentsContainer.scala
> +    extension [T <: Component](map: Map[Entity, T]) {
Comment these extension methods? It took a while for me to get what `-?` does by looking at its code alone.

2021-08-22 17:12 UTC, ndido98 commented on src/main/scala/dev/atedeg/ecscala/util/immutable/ComponentsContainer.scala
> +        componentsMap flatMap { (tt, componentMap) => (componentMap -? entity) map (tt -> _) }
Here you used curly braces in the `flatMap` and the round parentheses in the various `map`s above, what should we use and stick with?

2021-08-22 17:15 UTC, giacomocavalieri commented on src/main/scala/dev/atedeg/ecscala/util/immutable/ComponentsContainer.scala
> +        map filterNot ((e, c) => e == entity && c.eq(component))
If I recall correctly we said that, despite components being case classes, we should only remove them when the reference is exactly the same... however, thinking about it, it could make sense to rely on the case class equality method

2021-08-23 08:37 UTC, vitlinda commented on src/main/scala/dev/atedeg/ecscala/Entity.scala
> +  private[ecscala] def onAddedComponent(handler: ((Entity, TypeTag[Component], Component)) => Unit): Entity
It will be done in a future PR.

2021-08-23 09:22 UTC, ndido98 approved these changes

2021-08-23 09:22 UTC, nicolasfara approved these changes

2021-08-23 09:27 UTC, merged