Basic DSL implementation
nicolasfara/ecscala pull request #60
Opened 2021-08-27 11:03 UTC by vitlinda

This PR provides the Ecscala DSL basic functionalities such as:
- create an `Entity`
- add and remove components to an `Entity`

Close #58

2021-08-29 12:24 UTC, ndido98 commented on src/main/scala/dev/atedeg/ecscala/dsl/ExtensionMethods.scala
> +    def +[T <: Component: TypeTag](component: T): Entity = entity.addComponent(component)
Maybe `+=` so we better highlight the fact that this function has a side effect?

2021-08-29 13:12 UTC, giacomocavalieri commented on src/main/scala/dev/atedeg/ecscala/dsl/ExtensionMethods.scala
> +    def +[T <: Component: TypeTag](component: T): Entity = entity.addComponent(component)
In that case, when adding multiple components at a time it would look like this:
`entity += Position(1, 2) += Velocity(1, 2)` or `entity = entity += Position(1, 2) += Velocity(1, 2)`
A simple `+` might be better:
`entity + Position(1, 2) + Velocity(1, 2)` or `entity = entity + Position(1, 2) + Velocity(1, 2)`

2021-08-29 13:13 UTC, ndido98 approved these changes

2021-08-29 18:08 UTC, nicolasfara requested changes

2021-08-29 18:08 UTC, nicolasfara commented on README.md
Add imports for the DSL

2021-08-29 18:08 UTC, nicolasfara commented on core/src/main/scala/dev/atedeg/ecscala/dsl/EcscalaDSL.scala
> +   * } </pre>
Consider using `{{{ ... }}}` for code snippet in scaladoc.

2021-08-29 18:08 UTC, nicolasfara commented on core/src/main/scala/dev/atedeg/ecscala/dsl/ExtensionMethods.scala
> +     * <pre class="stHighlight"> entity withComponents {
Here and below in the file use `{{{ ... }}}` for code snippet

2021-08-29 18:08 UTC, nicolasfara commented on core/src/main/scala/dev/atedeg/ecscala/dsl/Words.scala
> +   * <pre class="stHighlight"> world hasAn entity </pre>
Same here: use `{{{ ... }}}`

2021-08-29 18:45 UTC, giacomocavalieri commented on README.md
>  @main def main(): Unit = {
I think that, in order to use the DSL, you have to create a `new ECSDSL{...}` or something like that

2021-08-29 18:45 UTC, giacomocavalieri commented on core/src/main/scala/dev/atedeg/ecscala/dsl/ExtensionMethods.scala
> +
Delete this empty line

2021-08-29 18:45 UTC, giacomocavalieri commented on core/src/test/scala/dev/atedeg/ecscala/dsl/EcscalaDSLTest.scala
> +
You could add one more test case where you chain only 2 components (e.g. `Position(1, 2) and Velocity(3, 4)`) so that you test the case where you do not call the `add` extension method of the `componentWrapper`

2021-08-29 18:45 UTC, giacomocavalieri commented on core/src/test/scala/dev/atedeg/ecscala/dsl/EcscalaDSLTest.scala
> +      world.getComponents[Position] should not contain (Map(entity1 -> position))
Here you should check that the `world.getComponents[Position]` is an empty `Option`

2021-08-29 18:45 UTC, giacomocavalieri commented on core/src/test/scala/dev/atedeg/ecscala/dsl/EcscalaDSLTest.scala
> +      world.getComponents[Position] should contain(Map(entity1 -> Position(1, 2)))
Since you have already defined the `position` variable you could use it in the check too:
```suggestion
      world.getComponents[Position] should contain(Map(entity1 -> position))
```

2021-08-29 18:45 UTC, giacomocavalieri commented on core/src/test/scala/dev/atedeg/ecscala/dsl/EcscalaDSLTest.scala
> +      val entity1 = world hasAn entity
Since you have only one entity in this test you could simply call it `entity` instead of `entity1`

2021-08-30 08:04 UTC, nicolasfara requested changes

2021-08-30 08:04 UTC, nicolasfara commented on core/src/main/scala/dev/atedeg/ecscala/dsl/ExtensionMethods.scala
> +     * } }}}
```
     * {{{
     * entity withComponents {
     *
     * Component1() and Component2()
     *
     * }
     * }}}
 ```

2021-08-30 08:04 UTC, nicolasfara commented on core/src/main/scala/dev/atedeg/ecscala/dsl/ExtensionMethods.scala
> +     * {{{entity + Component()}}}
Ditto

2021-08-30 08:04 UTC, nicolasfara commented on core/src/main/scala/dev/atedeg/ecscala/dsl/ExtensionMethods.scala
> +     * {{{entity - Component()}}}
Ditto

2021-08-30 08:04 UTC, nicolasfara commented on core/src/main/scala/dev/atedeg/ecscala/dsl/ExtensionMethods.scala
> +     * {{{world hasAn entity}}}
Ditto

2021-08-30 08:04 UTC, nicolasfara commented on core/src/main/scala/dev/atedeg/ecscala/dsl/ExtensionMethods.scala
> +     * } }}}
Ditto

2021-08-30 08:39 UTC, ndido98 approved these changes

2021-08-30 08:43 UTC, giacomocavalieri approved these changes

2021-08-30 08:43 UTC, giacomocavalieri commented on core/src/test/scala/dev/atedeg/ecscala/dsl/EcscalaDSLTest.scala
> +      }
This setup could be moved up to keep al checks near each other

2021-08-30 08:52 UTC, nicolasfara approved these changes

2021-08-30 08:55 UTC, merged