View
nicolasfara/ecscala pull request #62
Opened 2021-08-29 14:00 UTC by nicolasfara

Add the `View` trait.

2021-08-29 15:34 UTC, ndido98 requested changes

2021-08-29 15:34 UTC, ndido98 commented on core/src/main/scala/dev/atedeg/ecscala/CList.scala
> +    case CNil => "CNil"
I think it would be nicer if we didn't print `CNil`

2021-08-29 15:34 UTC, ndido98 commented on core/src/test/scala/dev/atedeg/ecscala/fixtures/ComponentsFixture.scala
> +
Why did you move these case classes outside the trait?

2021-08-29 15:34 UTC, ndido98 commented on core/src/main/scala/dev/atedeg/ecscala/util/macros/ViewMacro.scala
> +    }).asInstanceOf[L]
Why is this cast necessary?

2021-08-29 15:34 UTC, ndido98 commented on core/src/main/scala/dev/atedeg/ecscala/util/macros/ViewMacro.scala
> +          current = smallerMap flatMap (_.headOption) map (_.head)
I think I found a flaw in this line: when you iterate over the entities of the smaller map, you need to actually make sure that the new current has either all the required components, or there are no more entities left.
Suppose you have four entities in the world:
|                             |  1  |  2  |  3  |  4  |   5   |
|--------------------|------|----|----|-----|--|
| **Components** | ABC | BC | AB | C | ABC |

So the maps would be like so:
* A (smallest map): 1, 3, 5
* B: 1, 2, 3, 5
* C: 1, 2, 4, 5

At the first iteration `hasNext` is true, because `current` is `Some(1)` and 1 is present in all three maps; now I call `next` and `current` becomes `Some(3)`.
However, now `hasNext` returns false, because while `current` is defined, 3 is not present in all three maps. That means that as soon as I stumble upon an entity that by natural (non-deterministic) ordering does not have all the required components, this view will fail to return any subsequent entity.
In fact, what should have happened is that `next` should have set `current` to 5, because that entity still matches the filter required to the view.

2021-08-29 15:34 UTC, ndido98 commented on core/src/test/scala/dev/atedeg/ecscala/ViewTest.scala
> +  "A view" should {
Add the test case I mentioned in the View file.

2021-08-29 15:36 UTC, giacomocavalieri commented on core/src/main/scala/dev/atedeg/ecscala/CList.scala
> +    case CNil => "CNil"
What would you print otherwise?

2021-08-29 15:37 UTC, giacomocavalieri commented on core/src/test/scala/dev/atedeg/ecscala/fixtures/ComponentsFixture.scala
> +
Because otherwise it would make it harder to test the behaviour of the Views using a fixture

2021-08-29 15:38 UTC, giacomocavalieri commented on core/src/main/scala/dev/atedeg/ecscala/util/macros/ViewMacro.scala
> +    }).asInstanceOf[L]
It would not compile otherwise

2021-08-29 16:14 UTC, ndido98 commented on core/src/main/scala/dev/atedeg/ecscala/CList.scala
> +    case CNil => "CNil"
Right, then leave it as it is.

2021-08-29 16:52 UTC, ndido98 approved these changes

2021-08-29 17:55 UTC, vitlinda approved these changes

2021-08-30 08:37 UTC, giacomocavalieri approved these changes

2021-08-30 08:38 UTC, merged