System
nicolasfara/ecscala pull request #64
Opened 2021-09-02 16:17 UTC by giacomocavalieri

Closes #50 
Closes #51 
Closes #52 
Closes #53

2021-09-02 16:51 UTC, ndido98 requested changes

2021-09-02 16:51 UTC, ndido98 commented on core/src/main/scala/dev/atedeg/ecscala/System.scala
> +  def after(view: View[L]): Unit = {}
Add a Scaladoc for these two methods

2021-09-02 16:51 UTC, ndido98 commented on core/src/main/scala/dev/atedeg/ecscala/System.scala
> +  // type that has been erased.
Make it a Scaladoc?

2021-09-02 16:51 UTC, ndido98 commented on core/src/main/scala/dev/atedeg/ecscala/dsl/EcscalaDSL.scala
>  package dev.atedeg.ecscala.dsl
Rename the file as ECScalaDSL.scala

2021-09-02 16:51 UTC, ndido98 commented on core/src/main/scala/dev/atedeg/ecscala/util/macros/ViewMacro.scala
> +      .asInstanceOf[Seq[(ComponentTag[Component], Component)]]
Why is this cast safe? Explain in a comment

2021-09-02 16:51 UTC, ndido98 commented on core/src/main/scala/dev/atedeg/ecscala/util/macros/ViewMacro.scala
> +      .map(taggedMap => taggedMap._1 -> taggedMap._2(entity))
Remove the dot and parentheses for map

2021-09-02 16:51 UTC, ndido98 commented on core/src/main/scala/dev/atedeg/ecscala/util/macros/ViewMacro.scala
> +      .asInstanceOf[L]
Why is this cast safe? Explain in a comment

2021-09-02 16:51 UTC, ndido98 commented on core/src/test/scala/dev/atedeg/ecscala/dsl/EcscalaDSLTest.scala
Rename file in ECScalaDSLTest.scala

2021-09-02 17:44 UTC, nicolasfara approved these changes

2021-09-03 13:46 UTC, giacomocavalieri commented on core/src/main/scala/dev/atedeg/ecscala/System.scala
> +  def after(view: View[L]): Unit = {}
Why would you need a `World` parameter here? Should I add it to the `update` method too if I'm adding it?

2021-09-03 13:46 UTC, giacomocavalieri commented on core/src/main/scala/dev/atedeg/ecscala/System.scala
> +  // type that has been erased.
Even if the method is `private[ecscala]`?

2021-09-03 13:47 UTC, ndido98 commented on core/src/main/scala/dev/atedeg/ecscala/System.scala
> +  def after(view: View[L]): Unit = {}
The world parameter could be used if I need to add components/entities in those before/after methods, and we already have it in the update method

2021-09-03 13:48 UTC, ndido98 commented on core/src/main/scala/dev/atedeg/ecscala/System.scala
> +  // type that has been erased.
Yes, so it appears correctly using an IDE

2021-09-03 14:27 UTC, vitlinda approved these changes

2021-09-03 15:30 UTC, nicolasfara commented on core/src/main/scala/dev/atedeg/ecscala/util/macros/ViewMacro.scala
> +      .map(taggedMap => taggedMap._1 -> taggedMap._2(entity))
For symmetry with `foldRight` use the `.` also in `map`

2021-09-03 15:43 UTC, ndido98 approved these changes

2021-09-03 17:06 UTC, ndido98 approved these changes

2021-09-03 17:08 UTC, merged