Excluding views and systems
nicolasfara/ecscala pull request #73
Opened 2021-09-08 12:19 UTC by ndido98

Closes #70
Closes #72

As of submission, #71 is missing, I'm open to ideas on how to do it.

2021-09-08 15:22 UTC, giacomocavalieri requested changes

2021-09-08 15:22 UTC, giacomocavalieri commented on core/src/main/scala/dev/atedeg/ecscala/System.scala
> + * Represent a way to iterate over entities specific components (given by the type parameter L) and manupulate them.
Shouldn't it be `entities'`?

2021-09-08 15:22 UTC, giacomocavalieri commented on core/src/main/scala/dev/atedeg/ecscala/System.scala
> +  def before(deltaTime: DeltaTime, world: World, view: View[L]): Unit = {}
You are missing the doc for the new parameter

2021-09-08 15:22 UTC, giacomocavalieri commented on core/src/main/scala/dev/atedeg/ecscala/System.scala
> +  def after(deltaTime: DeltaTime, world: World, view: View[L]): Unit = {}
You are missing the doc for the new parameter

2021-09-08 15:22 UTC, giacomocavalieri commented on core/src/main/scala/dev/atedeg/ecscala/System.scala
> +    cltExcl: CListTag[LExcluded],
Why is only the `cltIncl` marked as a `private val`?

2021-09-08 15:22 UTC, giacomocavalieri commented on core/src/main/scala/dev/atedeg/ecscala/World.scala
> +   * LIncluded, that do not have any of the components listed in LEXcluded.
```suggestion
   * LIncluded, that do not have any of the components listed in LExcluded.
```

2021-09-08 15:22 UTC, giacomocavalieri commented on core/src/main/scala/dev/atedeg/ecscala/World.scala
> +  ): ExcludingView[LIncluded, LExcluded]
I think that in the trait you could simply write the method signature as 
```scala
def getView[LIncluded <: CList: CListTag, LExcluded <: CList: CListTag]: ExcludingView[LIncluded, LExcluded]
```

2021-09-08 15:22 UTC, giacomocavalieri commented on core/src/main/scala/dev/atedeg/ecscala/World.scala
> +  def addSystem[L <: CList](system: System[L])(using clt: CListTag[L]): Unit
Here too, there's no need to explicitly state the name of the CListTag in the trait, you could change it to:
```scala
addSystem[L <: CList: CListTag]
```

2021-09-08 15:22 UTC, giacomocavalieri commented on core/src/main/scala/dev/atedeg/ecscala/View.scala
> +    override def iterator: Iterator[(Entity, L)] = new ViewIterator[L](world)(using clt)
I think the type annotation on `[L]` `ViewIterator` is superfluous

2021-09-08 15:22 UTC, giacomocavalieri commented on core/src/main/scala/dev/atedeg/ecscala/View.scala
> +        new ExcludingViewIterator[LIncluded, LExcluded](world)(using cltIncl, cltExcl)
Same as above

2021-09-08 15:22 UTC, giacomocavalieri commented on core/src/main/scala/dev/atedeg/ecscala/View.scala
> +    override protected def isValid(entity: Entity): Boolean = maps.forall(_ contains entity)
Why is it `maps.forall` and not `otherMaps.forall`? Since entity is from the `smallerMap` it will always be contained in it

2021-09-08 15:22 UTC, giacomocavalieri commented on core/src/main/scala/dev/atedeg/ecscala/View.scala
> +    private val taggedExludingMaps = getMaps(world)(using cltExcl)
```suggestion
    private val taggedExcludingMaps = getMaps(world)(using cltExcl)
```

2021-09-08 17:31 UTC, nicolasfara approved these changes

2021-09-08 17:31 UTC, nicolasfara commented on core/src/main/scala/dev/atedeg/ecscala/View.scala
> + * LIncluded, that do not have any of the components listed in LEXcluded.
```suggestion
 * LIncluded, that do not have any of the components listed in LExcluded.
```

2021-09-08 17:31 UTC, nicolasfara commented on core/src/main/scala/dev/atedeg/ecscala/View.scala
> +    else optionalMaps map ((taggedMap) => taggedMap._1 -> taggedMap._2.get.asInstanceOf[Map[Entity, Component]])
Motivating the use of this cast can be useful or is it already clear?

2021-09-08 18:11 UTC, vitlinda approved these changes

2021-09-09 14:36 UTC, ndido98 commented
Closes #71

2021-09-09 14:39 UTC, giacomocavalieri approved these changes

2021-09-09 14:40 UTC, merged