DSL new syntax
nicolasfara/ecscala pull request #75
Opened 2021-09-10 21:42 UTC by vitlinda

This PR introduces the syntax to:

- remove more than one component from an entity
- add a `System` to a `World`
- get a `View` from a `World`

2021-09-12 08:00 UTC, ndido98 approved these changes

2021-09-12 08:40 UTC, nicolasfara approved these changes

2021-09-13 12:56 UTC, giacomocavalieri requested changes
One more thing I'm not really sure about: why are we adding all the complicated code to remove more components when we already have a CList which would be perfect and just as succinct as using `and`?
Is it really that better to write
```scala
remove comp1() and comp2() and comp3() from entity
```
rather than
```scala
remove comp1() &: comp2() &: comp3() from entity
```
Also, if you really want to keep the `and` why not use an underlying `CList` for the implementation rather than a map?

2021-09-13 12:56 UTC, giacomocavalieri commented on core/src/main/scala/dev/atedeg/ecscala/dsl/ECScalaDSL.scala
> + *   *  remove (entity1, entity2, entity3) from world
Here to remove multiple things we have a comma-separated list `entity1, entity2, ...`
However, to remove multiple components we use and-separated list `componen1 and component2 and ...`
I don't really like this little inconsistency, is there a way to have a unique way to specify more than one thing in this lists?

2021-09-13 12:56 UTC, giacomocavalieri commented on core/src/main/scala/dev/atedeg/ecscala/dsl/ECScalaDSL.scala
> + * '''Remove a components from an entity:'''
```suggestion
 * '''Remove components from an entity:'''
```

2021-09-13 12:56 UTC, giacomocavalieri commented on core/src/main/scala/dev/atedeg/ecscala/dsl/ECScalaDSL.scala
> + *   *  remove { MyComponent1() and MyComponent2 and MyComponent3 } from entity1
```suggestion
 *   *  remove { MyComponent1() and MyComponent2() and MyComponent3() } from entity1
```

2021-09-13 12:56 UTC, giacomocavalieri commented on core/src/main/scala/dev/atedeg/ecscala/dsl/ECScalaDSL.scala
> + * world hasA system[MyComponent() &: CNil] { (_,_,_) => {}}
Here you should not use parentheses, you are specifying a type, not passing an instance
```suggestion
 * world hasA system[MyComponent &: CNil] { (_,_,_) => {}}
```

2021-09-13 12:56 UTC, giacomocavalieri commented on core/src/main/scala/dev/atedeg/ecscala/dsl/ECScalaDSL.scala
> + *   val view = getView[MyComponent1() &: MyComponent2() &: CNil] from world
Same as above
```suggestion
 *   val view = getView[MyComponent1 &: MyComponent2 &: CNil] from world
```

2021-09-13 12:56 UTC, giacomocavalieri commented on core/src/test/scala/dev/atedeg/ecscala/dsl/ECScalaDSLTest.scala
> +  "The following syntax: world hasAn entity withComponents { Component 1 and Component2 }" should {
You are repeating `"The following syntax:"` before each test, are you sure there is not a way to factor it out?

2021-09-13 12:56 UTC, giacomocavalieri commented on core/src/test/scala/dev/atedeg/ecscala/dsl/ECScalaDSLTest.scala
> +  "The following syntax world - myEntity" should {
```suggestion
  "The following syntax: world - myEntity" should {
```

2021-09-15 08:33 UTC, ndido98 approved these changes

2021-09-15 08:48 UTC, nicolasfara approved these changes

2021-09-15 14:22 UTC, giacomocavalieri requested changes

2021-09-15 14:22 UTC, giacomocavalieri commented on core/src/main/scala/dev/atedeg/ecscala/dsl/ECScalaDSL.scala
> +  class FromEntity(componentList: CList)(using clt: CListTag[? <: CList]) {
Why are you passing a `CList` and not using a generic type `L <: CList` (like in `ViewFromWorld`)? It would also simplify the `clt` type:
```suggestion
  class FromEntity[L <: CList](componentList: L)(using clt: CListTag[L]) {
```

2021-09-15 14:22 UTC, giacomocavalieri commented on core/src/main/scala/dev/atedeg/ecscala/dsl/ECScalaDSL.scala
> +      componentList zip clt.tags.asInstanceOf[Seq[ComponentTag[Component]]] foreach {
We could consider moving this `asInstanceOf` directly in the `CListTag.tags` method (which would return a `Seq[ComponentTag[Component]]`), I think we used the same cast in Views too. What do you think @vitlinda @ndido98 @nicolasfara?

2021-09-15 14:22 UTC, giacomocavalieri commented on core/src/main/scala/dev/atedeg/ecscala/dsl/ECScalaDSL.scala
> +     *   getView[MyComponent1() &: MyComponent2() &: CNil] from world
```suggestion
     *   getView[MyComponent1 &: MyComponent2 &: CNil] from world
```

2021-09-15 14:22 UTC, giacomocavalieri commented on core/src/main/scala/dev/atedeg/ecscala/dsl/ECScalaDSL.scala
> +  private[dsl] case class ClearWord()
Why a `case class` and not a `case object`?

2021-09-15 14:22 UTC, giacomocavalieri commented on core/src/test/scala/dev/atedeg/ecscala/WorldTest.scala
> +    "has 3 entities " should {
```suggestion
    "has 3 entities" should {
```

2021-09-15 14:22 UTC, giacomocavalieri commented on core/src/test/scala/dev/atedeg/ecscala/dsl/ECScalaDSLTest.scala
> +      }
You could one-line this part
```suggestion
      val entity1 = world hasAn entity withComponents { position &: velocity }
```

2021-09-15 14:22 UTC, giacomocavalieri commented on core/src/test/scala/dev/atedeg/ecscala/dsl/ECScalaDSLTest.scala
> +      } from entity1
This part could also be written in one line
```suggestion
      remove { position &: CNil } from entity1
```

2021-09-15 14:22 UTC, giacomocavalieri commented on core/src/test/scala/dev/atedeg/ecscala/dsl/ECScalaDSLTest.scala
> +  "remove { Component1() &: Component2() from world" should {
```suggestion
  "remove { Component1() &: Component2() } from world" should {
```

2021-09-15 14:22 UTC, giacomocavalieri commented on core/src/test/scala/dev/atedeg/ecscala/dsl/ECScalaDSLTest.scala
> +      } from entity1
This code could be way more compact
```suggestion
      val entity1 = world hasAn entity withComponents { position &: velocity }
      remove { position &: velocity } from entity1
```

2021-09-15 14:22 UTC, giacomocavalieri commented on core/src/test/scala/dev/atedeg/ecscala/dsl/ECScalaDSLTest.scala
> +    "work the same way ad the world.removeEntity() method" in new WorldFixture {
```suggestion
    "work the same way as the world.removeEntity() method" in new WorldFixture {
```

2021-09-15 14:22 UTC, giacomocavalieri commented on core/src/test/scala/dev/atedeg/ecscala/dsl/ECScalaDSLTest.scala
> +      } from world
Could be written in one line 
```suggestion
      remove { entity1 } from world
```

2021-09-15 14:22 UTC, giacomocavalieri commented on core/src/test/scala/dev/atedeg/ecscala/dsl/ECScalaDSLTest.scala
> +      } from world
Could be written in one line 
```suggestion
      remove { List(entity2, entity3, entity4) } from world
```

2021-09-15 14:22 UTC, giacomocavalieri commented on core/src/test/scala/dev/atedeg/ecscala/dsl/ECScalaDSLTest.scala
> +  "remove (entity1, entity2) from world" should {
Also this string describes an old test with a syntax that is no longer allowed, you should test (in separate cases) the `remove (entity) from world` and the `remove (Seq(e1, e2, ...)) from world`

2021-09-15 14:22 UTC, giacomocavalieri commented on core/src/main/scala/dev/atedeg/ecscala/dsl/ECScalaDSL.scala
> + * world hasA system[MyComponent &: CNil] { (_,_,_) => {}}
Does this expression return the `System` that was actually added? Meaning that you could write an expression like this:
```scala
val system = world hasA system[Comp &: CNil] { ??? }
```

2021-09-15 15:01 UTC, vitlinda commented on core/src/test/scala/dev/atedeg/ecscala/dsl/ECScalaDSLTest.scala
> +      } from world
scalafmt must have gone crazy

2021-09-15 15:01 UTC, vitlinda commented on core/src/test/scala/dev/atedeg/ecscala/dsl/ECScalaDSLTest.scala
> +      } from world
here as well

2021-09-20 12:12 UTC, giacomocavalieri approved these changes

2021-09-20 19:34 UTC, merged