Add Scalafx demo baseline
nicolasfara/ecscala pull request #93
Opened 2021-09-21 10:09 UTC by nicolasfara

2021-09-21 11:39 UTC, vitlinda approved these changes

2021-09-21 15:23 UTC, nicolasfara commented on demo/src/main/scala/dev/atedeg/ecscalademo/controller/GameLoop.scala
> +        currentFps
This method calculate the FPS of the scene. The observable value `fps` is updated and showed in the right corner of the UI.
The [AnimationTimer](https://docs.oracle.com/javase/8/javafx/api/javafx/animation/AnimationTimer.html) class try to mantain 60 FPS, on each frame a new time is given to the `handle` method and with that value we calculate the FPS value.
After each update of the FPS the observable value is updated and the new value is returned.

2021-09-21 15:24 UTC, nicolasfara commented on demo/src/main/scala/dev/atedeg/ecscalademo/controller/MainViewController.scala
> +class MainViewController extends Initializable {
No, this class is the Controller for the FXML file, in order to achive a binding between UI and Scala code.

2021-09-21 15:24 UTC, nicolasfara commented on demo/src/test/scala/dev/atedeg/ecscalademo/MathTest.scala
> +      "add it" in {
@ndido98 what do you think?

2021-09-21 15:28 UTC, nicolasfara commented on demo/src/main/scala/dev/atedeg/ecscalademo/Math.scala
> +  def dot(vector: Vector) = x * vector.x + y * vector.y
Using that character, the compiler say: `illegal character \u2022`

2021-09-21 15:34 UTC, vitlinda commented on demo/src/main/scala/dev/atedeg/ecscalademo/SimulationStatus.scala
> +  var lastBallAdded = 0
It's used in @ndido98 ' s example to prevent multiple ball addition in a low range of milliseconds.
I'm gonna rename it in: `lastBallAddedTimeStamp`

2021-09-22 09:14 UTC, giacomocavalieri commented on demo/src/main/scala/dev/atedeg/ecscalademo/SimulationStatus.scala
> +  var lastBallAdded = 0
Didn't we decide to remove this limitation? I remember it being absent in the last demo @ndido98 showed us

2021-09-22 09:15 UTC, giacomocavalieri commented on demo/src/main/scala/dev/atedeg/ecscalademo/controller/GameLoop.scala
> +        currentFps
So its an `FPSCount` rather than an `FPSCounter`?

2021-09-22 09:28 UTC, ndido98 approved these changes

2021-09-22 09:39 UTC, giacomocavalieri commented on demo/src/test/scala/dev/atedeg/ecscalademo/MathTest.scala
> +      }
This should be changed, you are not `"adding another vector"`; they should be moved to their own `when`:
```suggestion
    "subtracting another vector" should {
      "return the correct result" in {
        Vector(1, 1) - Vector(2, 2) shouldBe Vector(-1, -1)
      }
    }
    "computing the dot product" should {
      "return the correct result" in {
        Vector(1, 2) dot Vector(3, 4) shouldBe 11
      }
    }
```

2021-09-22 21:44 UTC, ndido98 requested changes

2021-09-22 21:44 UTC, ndido98 commented on demo/src/main/scala/dev/atedeg/ecscalademo/ECSCanvas.scala
> +  }
Instead of `Coordinates` use `Point`

2021-09-22 21:44 UTC, ndido98 commented on demo/src/main/scala/dev/atedeg/ecscalademo/ECSCanvas.scala
> +  def drawCircle(coordinates: Coordinates, radius: Double, color: Color, lineWidth: Double): Unit = {
You ignore the color parameter

2021-09-22 21:44 UTC, ndido98 commented on demo/src/main/scala/dev/atedeg/ecscalademo/ECSCanvas.scala
> +  def drawLine(elementPosition: Coordinates, mousePosition: Coordinates): Unit = {
Change the arguments names to something like `from` and `to`. I'd add the `color` and the `lineWidth` parameters.

2021-09-22 21:44 UTC, ndido98 commented on demo/src/main/scala/dev/atedeg/ecscalademo/ECSCanvas.scala
> +  }
What's this method?

2021-09-23 07:12 UTC, giacomocavalieri requested changes

2021-09-23 07:12 UTC, giacomocavalieri commented on demo/src/main/scala/dev/atedeg/ecscalademo/Components.scala
> +case class Coordinates(x: Double, y: Double)
What's the difference between `Coordinates` and `Point`?

2021-09-23 07:12 UTC, giacomocavalieri commented on demo/src/main/scala/dev/atedeg/ecscalademo/ECSCanvas.scala
> +case class ECSCanvas(canvas: Canvas) {
I don't really like this solution: we still have a strong dependency with the `scalafx.Canvas` since it is in the constructor of our `ECSCanvas`. It would be better to have a `trait ECSCanvas` that only specifies the `drawCircle`, `drawLine` methods and leave the specific implementations to choose which canvas to use.
Imagine in the future you want to use ScalaSwing instead: instead of creating a new `ECSCanvasImpl` which uses the Swing canvas, you have to change preexisting code since you hard coded the type of the canvas used internally by the `ECSCanvas` to be a `scalafx.canvas`

2021-09-23 07:29 UTC, giacomocavalieri approved these changes

2021-09-23 07:30 UTC, ndido98 approved these changes

2021-09-23 07:33 UTC, merged