Add creation, rendering, selection and drag ball systems
nicolasfara/ecscala pull request #96
Opened 2021-09-25 15:56 UTC by nicolasfara

This PR add the followig systems:
  - `BallCreationSystemRendering`: render the ball when in creation mode
  - `BallCreationSystem`: add a ball in the world
  - `BallSelectionSystem`: when the game is paused, this system select a ball
  - `DragBallSystem`: move the selected ball when the game is paused

Closes #89
Closes #90

2021-09-25 17:23 UTC, ndido98 requested changes

2021-09-25 17:23 UTC, ndido98 commented on demo/src/main/scala/dev/atedeg/ecscalademo/systems/BallCreationSystem.scala
> +    (point - MouseState.coordinates).norm < (radius + StartingState.startingRadius)
You can use `squaredNorm` on the left and `math.pow(..., 2)` on the right to avoid the square root

2021-09-25 17:23 UTC, ndido98 commented on demo/src/main/scala/dev/atedeg/ecscalademo/systems/BallSelectionSystem.scala
> +    (MouseState.coordinates - point).norm < (radius + StartingState.startingRadius)
Ditto

2021-09-25 17:53 UTC, giacomocavalieri requested changes

2021-09-25 17:53 UTC, giacomocavalieri commented on core/src/main/scala/dev/atedeg/ecscala/System.scala
> + * A [[System]] that not iterate over any [[Component]].
```suggestion
 * A [[System]] that does not iterate over any [[Component]].
```

2021-09-25 17:53 UTC, giacomocavalieri commented on core/src/main/scala/dev/atedeg/ecscala/System.scala
> +  def update(deltaTime: DeltaTime, world: World): Unit
Missing documentation

2021-09-25 17:53 UTC, giacomocavalieri commented on core/src/test/scala/dev/atedeg/ecscala/SystemTest.scala
> +      world.addSystem(EmptySystem((dt, w) => success = true))
```suggestion
      world.addSystem(EmptySystem((_, _) => success = true))
```

2021-09-25 17:53 UTC, giacomocavalieri commented on demo/src/main/scala/dev/atedeg/ecscalademo/Components.scala
> +given Conversion[Position, Point] = _.position
Instead of an implicit conversion you could create a companion object like this:
```scala
object Position {
  def apply(x: Double, y: Double): Position = Position(Point(x, y))
}
```

2021-09-25 17:53 UTC, giacomocavalieri commented on demo/src/main/scala/dev/atedeg/ecscalademo/Components.scala
> +given Conversion[Velocity, Vector] = _.velocity
Same as before

2021-09-25 17:53 UTC, giacomocavalieri commented on demo/src/main/scala/dev/atedeg/ecscalademo/systems/BallCreationRenderingSystem.scala
> +  override def shouldRun: Boolean = !PlayState.playing
It should run only if you are adding balls, not when the game is paused

2021-09-25 17:53 UTC, giacomocavalieri commented on demo/src/main/scala/dev/atedeg/ecscalademo/systems/BallCreationSystem.scala
> + * This [[System]] is used to create a new ball into the [[World]]. If the mouse pointer is in the area of another ball,
```suggestion
 * This [[System]] is used to add a new ball into the [[World]]. If the mouse pointer is in the area of another ball,
```

2021-09-25 17:53 UTC, giacomocavalieri commented on demo/src/main/scala/dev/atedeg/ecscalademo/systems/BallCreationSystem.scala
> +  override def shouldRun: Boolean = MouseState.clicked && !PlayState.playing
It should run only if you are adding balls, not when the game is paused

2021-09-25 17:53 UTC, giacomocavalieri commented on demo/src/main/scala/dev/atedeg/ecscalademo/systems/BallCreationSystem.scala
> +          Mass(StartingState.startingMass)
Did scalafmt force you to indent the following lines? I think this would be nicer
```suggestion
        Position(MouseState.coordinates) &:
        Circle(StartingState.startingRadius, StartingState.startingColor) &:
        Velocity(Vector(0, 0)) &:
        Mass(StartingState.startingMass)
```

2021-09-25 17:53 UTC, giacomocavalieri commented on demo/src/main/scala/dev/atedeg/ecscalademo/systems/BallCreationSystem.scala
> +          Velocity(Vector(0, 0)) &:
Add `Vector(0, 0)` to the `StartingState` as `startingVelocity`

2021-09-25 17:53 UTC, giacomocavalieri commented on demo/src/main/scala/dev/atedeg/ecscalademo/systems/BallSelectionSystem.scala
> +    val entitySelected: Option[Entity] = world.getView[Position &: Circle &: CNil] find { e =>
```suggestion
    val selectedEntity: Option[Entity] = world.getView[Position &: Circle &: CNil] find { e =>
```

2021-09-25 17:53 UTC, giacomocavalieri commented on demo/src/main/scala/dev/atedeg/ecscalademo/systems/BallSelectionSystem.scala
> +    (MouseState.coordinates - point).norm < (radius + StartingState.startingRadius)
You repeated this code in `BallCreationSystem`, you could add an extension method to `Point` like `point isOverlapping otherPoint`

2021-09-25 17:53 UTC, giacomocavalieri commented on demo/src/main/scala/dev/atedeg/ecscalademo/systems/DragBallSystem.scala
> + * This [[System]] is used to update selected ball's position according to the mouse pointer.
```suggestion
 * This [[System]] is used to update the selected ball's [[Position]] according to the mouse pointer.
```

2021-09-25 17:53 UTC, giacomocavalieri commented on demo/src/main/scala/dev/atedeg/ecscalademo/systems/DragBallSystem.scala
> +    }
It should have a more sophisticated logic in the `shouldRun` method, we have to talk about it in depth

2021-09-25 17:53 UTC, giacomocavalieri commented on demo/src/test/scala/dev/atedeg/ecscalademo/systems/BallCreationRenderingSystemTest.scala
> +      "enabled" in new BallCreationRenderingSystemFixture {
```suggestion
      "be enabled" in new BallCreationRenderingSystemFixture {
```

2021-09-25 17:53 UTC, giacomocavalieri commented on demo/src/test/scala/dev/atedeg/ecscalademo/systems/BallCreationRenderingSystemTest.scala
> +    "the game is run" should {
```suggestion
    "the game is running" should {
```

2021-09-25 17:53 UTC, giacomocavalieri commented on demo/src/test/scala/dev/atedeg/ecscalademo/systems/BallCreationRenderingSystemTest.scala
> +        PlayState.playing = false
You should use `enableSystemCondition()`

2021-09-25 17:53 UTC, giacomocavalieri commented on demo/src/test/scala/dev/atedeg/ecscalademo/systems/BallCreationRenderingSystemTest.scala
> +      "disabled" in new BallCreationRenderingSystemFixture {
This test should not be here: it reads like `"A system when the game is run should disabled"`, it should become `"...when the game is run should be disabled"`

2021-09-25 17:53 UTC, giacomocavalieri commented on demo/src/test/scala/dev/atedeg/ecscalademo/systems/BallCreationRenderingSystemTest.scala
> +      }
When the game is stopped it should be enabled

2021-09-25 17:53 UTC, giacomocavalieri commented on demo/src/test/scala/dev/atedeg/ecscalademo/systems/BallCreationSystemTest.scala
> +    "the mouse is clicked and game not run" should {
```suggestion
    "the mouse is clicked and the game is not running" should {
```

2021-09-25 17:53 UTC, giacomocavalieri commented on demo/src/test/scala/dev/atedeg/ecscalademo/systems/BallCreationSystemTest.scala
> +    "the mouse is not clicked and game not run" should {
```suggestion
    "the mouse is not clicked and game is not running" should {
```

2021-09-25 17:53 UTC, giacomocavalieri commented on demo/src/test/scala/dev/atedeg/ecscalademo/systems/BallCreationSystemTest.scala
> +      "not create a ball when the mouse is inside other ball" in new BallCreationSystemFixture {
```suggestion
      "not create a ball when the mouse is inside another ball" in new BallCreationSystemFixture {
```

2021-09-25 17:53 UTC, giacomocavalieri commented on demo/src/test/scala/dev/atedeg/ecscalademo/systems/BallSelectionSystemTest.scala
> +      "set the ball as current selected" in new BallSelectionSystemFixture {
```suggestion
      "set the ball as currently selected" in new BallSelectionSystemFixture {
```

2021-09-25 17:53 UTC, giacomocavalieri commented on demo/src/test/scala/dev/atedeg/ecscalademo/systems/DragBallSystemTest.scala
> +      }
You are not checking anything and there is an equal test two lines below

2021-09-25 17:53 UTC, giacomocavalieri commented on demo/src/test/scala/dev/atedeg/ecscalademo/systems/DragBallSystemTest.scala
> +        } shouldBe Position(Point(0, 0))
This check is not requires, you are not testing the correct working of `addComponent`, you assume it is working correctly

2021-09-26 06:56 UTC, nicolasfara commented on demo/src/main/scala/dev/atedeg/ecscalademo/systems/BallCreationSystem.scala
> +          Mass(StartingState.startingMass)
I agree with you but scalafmt forces me to use that formatting...

2021-09-26 07:06 UTC, nicolasfara commented on demo/src/main/scala/dev/atedeg/ecscalademo/systems/BallSelectionSystem.scala
> +    (MouseState.coordinates - point).norm < (radius + StartingState.startingRadius)
Your idea is great, but i need the `radius` that is a property of the  `Circle` class, so I cannot create an extension method of `Point` since i need the `radius` in the formula.

2021-09-26 13:21 UTC, vitlinda approved these changes

2021-09-26 13:34 UTC, giacomocavalieri commented on demo/src/test/scala/dev/atedeg/ecscalademo/systems/BallSelectionSystemTest.scala
> +import dev.atedeg.ecscalademo.given
Do you still need this implicit conversion?

2021-09-26 13:35 UTC, giacomocavalieri commented on demo/src/test/scala/dev/atedeg/ecscalademo/systems/DragBallSystemTest.scala
> +import dev.atedeg.ecscalademo.given
Do you still need this implicit conversion?

2021-09-26 13:36 UTC, giacomocavalieri commented on demo/src/main/scala/dev/atedeg/ecscalademo/systems/BallSelectionSystem.scala
> +    (MouseState.coordinates - point).norm < (radius + StartingState.startingRadius)
Well you could still try to not repeat the same exact code in both files

2021-09-26 13:41 UTC, vitlinda requested changes

2021-09-26 13:41 UTC, vitlinda commented on core/src/test/scala/dev/atedeg/ecscala/SystemTest.scala
> +      world.addSystem(EmptySystem((_, _) => success = true))
You are not using the DSL

2021-09-26 13:41 UTC, vitlinda commented on demo/src/test/scala/dev/atedeg/ecscalademo/systems/BallCreationRenderingSystemTest.scala
> +        world.addSystem(system)
DSL missing

2021-09-26 13:41 UTC, vitlinda commented on demo/src/test/scala/dev/atedeg/ecscalademo/systems/BallCreationSystemTest.scala
> +    existingEntity.addComponent(Position(existingPosition))
Missing DSL in the whole file

2021-09-26 13:41 UTC, vitlinda commented on demo/src/test/scala/dev/atedeg/ecscalademo/systems/BallSelectionSystemTest.scala
> +        val entity1 = world.createEntity()
Missing DSL in the whole file

2021-09-26 13:41 UTC, vitlinda commented on demo/src/test/scala/dev/atedeg/ecscalademo/systems/DragBallSystemTest.scala
> +        entity.addComponent(Position(0.0, 0.0))
Missing DSL in the whole file

2021-09-26 14:39 UTC, vitlinda approved these changes

2021-09-27 13:49 UTC, vitlinda approved these changes

2021-09-27 14:04 UTC, ndido98 requested changes

2021-09-27 14:04 UTC, ndido98 commented on demo/src/main/scala/dev/atedeg/ecscalademo/Math.scala
> +    (this - otherPoint).squaredNorm < Math.pow(thisRadius + otherRadius, 2)
Move this to an extension method instead of inside the point class

2021-09-27 14:04 UTC, ndido98 commented on demo/src/main/scala/dev/atedeg/ecscalademo/SimulationStatus.scala
> +  var velocityChainging: Boolean = false
*changing

2021-09-27 16:08 UTC, giacomocavalieri commented on demo/src/main/scala/dev/atedeg/ecscalademo/SimulationStatus.scala
> +  var velocityChanging: Boolean = false
I would call this `velocityEditingMode` to be more in line with the `addBallMode` name

2021-09-27 16:08 UTC, giacomocavalieri approved these changes

2021-09-27 17:12 UTC, ndido98 approved these changes

2021-09-27 18:49 UTC, merged