Collisions system
nicolasfara/ecscala pull request #99
Opened 2021-09-26 09:38 UTC by ndido98

Close #86

2021-09-26 10:50 UTC, nicolasfara requested changes

2021-09-26 10:50 UTC, nicolasfara commented on demo/src/main/scala/dev/atedeg/ecscalademo/util/SpacePartitionContainer.scala
> +trait SpacePartitionContainer extends Iterable[((Int, Int), Seq[Entity])] {
Missing doc

2021-09-26 10:50 UTC, nicolasfara commented on demo/src/main/scala/dev/atedeg/ecscalademo/util/SpacePartitionContainer.scala
> +trait WritableSpacePartitionContainer extends SpacePartitionContainer {
ditto

2021-09-26 10:50 UTC, nicolasfara commented on core/src/test/scala/dev/atedeg/ecscala/SystemTest.scala
> +      world.addSystem(EmptySystem((dt, world) => success = true))
```suggestion
      world.addSystem(EmptySystem((_, _) => success = true))
```

2021-09-26 11:12 UTC, ndido98 commented on demo/src/main/scala/dev/atedeg/ecscalademo/Components.scala
> +given Conversion[Position, Point] = _.position
For convenience, so you don't have to unpack every time the position/velocity components.

2021-09-26 11:24 UTC, nicolasfara approved these changes

2021-09-26 13:38 UTC, vitlinda requested changes

2021-09-26 13:38 UTC, vitlinda commented on demo/src/main/scala/dev/atedeg/ecscalademo/Math.scala
> +given Conversion[(Double, Double), Point] = tuple => Point(tuple._1, tuple._2)
This was supposed to be removed, wasn't it?

2021-09-26 13:38 UTC, vitlinda commented on demo/src/main/scala/dev/atedeg/ecscalademo/Math.scala
> +
Same here

2021-09-26 13:38 UTC, vitlinda commented on demo/src/test/scala/dev/atedeg/ecscalademo/fixtures/CollisionsFixture.scala
> +  world addSystem (new RegionAssignmentSystem(spacePartition))
You are not using the DSL

2021-09-26 13:38 UTC, vitlinda commented on demo/src/test/scala/dev/atedeg/ecscalademo/fixtures/RegionAssignmentFixture.scala
> +  val entity1 = world.createEntity()
Not using the DSL in the whole file

2021-09-26 13:38 UTC, vitlinda commented on demo/src/test/scala/dev/atedeg/ecscalademo/fixtures/WallCollisionsFixture.scala
> +  }
Same here

2021-09-26 13:38 UTC, vitlinda commented on demo/src/test/scala/dev/atedeg/ecscalademo/systems/CollisionSystemTest.scala
> +class CollisionSystemTest extends AnyWordSpec with Matchers {
And here

2021-09-26 13:38 UTC, vitlinda commented on demo/src/test/scala/dev/atedeg/ecscalademo/systems/RegionAssignmentSystemTest.scala
> +      world.addSystem(new RegionAssignmentSystem(spacePartition))
In this line too

2021-09-26 13:38 UTC, vitlinda commented on demo/src/test/scala/dev/atedeg/ecscalademo/systems/WallCollisionSystemTest.scala
> +      val view = world.getView[Position &: Velocity &: CNil]
DSL missing

2021-09-26 13:38 UTC, vitlinda commented on demo/src/test/scala/dev/atedeg/ecscalademo/systems/WallCollisionSystemTest.scala
> +      val view = world.getView[Position &: Velocity &: CNil]
DSL missing

2021-09-26 13:48 UTC, ndido98 commented on demo/src/test/scala/dev/atedeg/ecscalademo/fixtures/CollisionsFixture.scala
> +  world addSystem (new RegionAssignmentSystem(spacePartition))
I don't have the method since you introduced it in your PR and I can't find the hash of the commit that introduced that change. Could you find it for me?

2021-09-26 14:07 UTC, giacomocavalieri requested changes

2021-09-26 14:07 UTC, giacomocavalieri commented on demo/src/main/scala/dev/atedeg/ecscalademo/util/SpacePartitionContainer.scala
> +        acc + (region -> (acc get region map (_ :+ elem) getOrElse List(elem)))
I would break this line down, it very hard to read and understand

2021-09-26 14:07 UTC, giacomocavalieri commented on demo/src/main/scala/dev/atedeg/ecscalademo/util/SpacePartitionContainer.scala
> +    override def get(region: (Int, Int)): Seq[Entity] = regions.getOrElse(region, Seq())
```suggestion
    override def get(region: (Int, Int)): Seq[Entity] = regions getOrElse (region, Seq())
```

2021-09-26 14:07 UTC, giacomocavalieri commented on demo/src/main/scala/dev/atedeg/ecscalademo/systems/CollisionSystem.scala
> +  ) = comparer((positions._1 - positions._2).squaredNorm, math.pow(radii._1 + radii._2, 2))
I would move this right below `isStuck`

2021-09-26 14:07 UTC, giacomocavalieri commented on demo/src/main/scala/dev/atedeg/ecscalademo/systems/CollisionSystem.scala
> +    val (massA, massB) = masses
Why are you passing the positions, velocities and masses as tuples if you end up unpacking them immediately?

2021-09-26 14:23 UTC, ndido98 commented on demo/src/main/scala/dev/atedeg/ecscalademo/systems/CollisionSystem.scala
> +    val (massA, massB) = masses
So should I just take two distinct parameters for each type?

2021-09-26 14:40 UTC, nicolasfara commented on demo/src/main/scala/dev/atedeg/ecscalademo/Components.scala
> +}
Maybe the @ndido98 is better: in my version the `new` is mandatory

2021-09-26 16:15 UTC, vitlinda approved these changes

2021-09-27 16:11 UTC, giacomocavalieri commented on demo/src/main/scala/dev/atedeg/ecscalademo/systems/CollisionSystem.scala
> +    val (massA, massB) = masses
I don't know... I'm not sure which one would look better, maybe you implementation is actually better

2021-09-27 19:11 UTC, giacomocavalieri approved these changes

2021-09-27 19:12 UTC, merged